### ISSUE TITLE
Extend this lib to work with other airlines

### ISSUE THREAD

**Issue by nextglabs** [JonHurst/aimslib#1]
Hello, I found this lib while making some research and I'm impressed! Great job! 

I'm trying to make this work with other airlines but I'm getting some errors. Would you like to have a chat to see what can be done? 

Looking forward to your reply.

**Comment by JonHurst** [comment]
Hi nextglabs, can you be more specific about what you are trying to do and where you are getting errors.

**Comment by nextglabs** [comment]
Hi @JonHurs, thanks for your reply.

I'm unable to parse the crews so far, as it's quite different from WizzAir. Any chance to discuss this during a Zoom call or equivalent to explain better what I'm trying to achieve?

**Comment by JonHurst** [comment]
I'm not a massive fan of video chat to be honest, but feel free to email me details at hursts.org+aimslib@gmail.com
and I'll see if there is anything I can do to help.
